### ISSUE TITLE
windows/osx dependenices

### ISSUE THREAD

**Issue by missinglink** [pelias/packer#1]
we have some chef recipes that are specific for windows, such as `https://github.com/chef-cookbooks/windows.git` and `https://github.com/chef-cookbooks/mingw.git`.

it might be worth keeping them if we intend on supporting windows desktop and cloud platforms, otherwise, we might be able to remove them to simplify the setup.

**Comment by dianashk** [comment]
Now that we have the docker compose setup could that be the preferred way
to install Pelias on Windows? We'd need to test it out, if course.

**Comment by missinglink** [comment]
I don't think `docker-compose` would be suitable for production installations, also AFAIK docker doesn't run natively on windows?

**Comment by missinglink** [comment]
we also have a production dependency on `https://github.com/chef-cookbooks/homebrew.git`

**Comment by orangejulius** [comment]
If i remember correctly, all of these windows and homebrew packages are dependencies of other packages we do use. We don't use them but can't do much about them without forking our dependency packages.
